### ISSUE TITLE
feature: 전체 동의

### ISSUE THREAD

**Issue by SeungAh-Yoo99** [woorifisa-service-dev-3rd/frontend-1st-smile_project#28]
## 💡 Issue

전체 동의 버튼 구현

## 📝 todo

- [ ] 전체 동의 버튼 눌렀을 경우, 다른 동의 버튼 2개 자동 체크
- [ ] 다른 동의 버튼 두개 모두 체크했을 경우, 전체 동의 버튼도 자동 체크
- [ ] 다른 동의 버튼 중 어느 하나 체크를 풀었을 경우, 전체 동의 버튼 체크 해제
