### ISSUE TITLE
feature: 인증서별 간편인증 헤더 변경

### ISSUE THREAD

**Issue by seonmin5** [woorifisa-service-dev-3rd/frontend-1st-smile_project#31]
## 💡 Issue
우리인증서 클릭 시, 우측 상단 헤더가 간편인증 → 우리인증서 아이콘 우리인증서로 변경
![image](https://github.com/user-attachments/assets/4591fff7-3a61-4c18-a60e-3e5efdfb3b3e)

## 📝 todo
- [x] 클릭 시 아이콘 뜨기
- [x] 아이콘에 맞추어 이름 뜨기
- [x] 우리인증서, 토스, 신한인증서, 삼성패스, 뱅크샐러드, 페이코, PASS, NH인증서, 네이버, 국민인증서, 카카오톡, 카카오뱅크, 하나인증서, 드림인증 반영 확인
