### ISSUE TITLE
feature: 인증 요청 정보 확인

### ISSUE THREAD

**Issue by SeungAh-Yoo99** [woorifisa-service-dev-3rd/frontend-1st-smile_project#38]
## 💡 Issue
인증 요청 시, 정보가 모두 올바르게 입력되었는지 확인
정보가 올바르게 입력되지 않았다면, 해당 칸에 주의 표시

## 📝 todo

- [x] 인증서 선택을 했는지 확인
- [x] 이름 입력했는지 확인
- [x] 생년월일 8자리로 올바르게 입력되었는지 확인
- [x] 통신사 선택했는지 확인
- [x] 휴대폰 번호 8자리 올바르게 입력되었는지 확인
- [x] 서비스 이용 동의 체크했는지 확인
